GET http://localhost:8081/dutyStatistics/subClassCount?startDate=&endDate=
Accept: application/json

###
GET http://localhost:8081/dutyStatistics/getDutyObjects?startDate=&endDate=
Accept: application/json

###
GET http://localhost:8081/dutyStatistics/getDutyObjectsRoutes?startDate=&endDate=&dutyObjectId=59e048ae-baf6-4fed-8e68-abf412d0e46b
Accept: application/json

###
GET http://localhost:8081/dutyStatistics/surfacing?startDate=&endDate=
Accept: application/json

###
GET http://localhost:8081/dutyStatistics/engineOperating?startDate=&endDate=
Accept: application/json

###
GET http://localhost:8081/dutyStatistics/engineResourceRemaining?startDate=&endDate=
Accept: application/json

###

GET http://localhost:8081/dutyStatistics/annualNormExceeding?startDate=&endDate=
Accept: application/json

###

GET http://localhost:8081/dutyStatistics/totalNormExceeding?startDate=&endDate=
Accept: application/json

###